/* global Utils */

/*
**********************************************************************
 * File       : scripts/diagnostics/displayTestResults.js
 * Author     : Edmund Mulligan <edmund@edmundmulligan.name>
 * Copyright  : (c) 2026 The Embodied Mind
 * License    : MIT License (see ../license-and-credits.html page)
 * Description:
 *    JavaScript for Test Results Dashboard - loads and displays
 *    automated test results with modal details view
 *    Requires: utils.js (for Utils.escapeHtml, Utils.loadJSON, Utils.isEmpty)
**********************************************************************
*/

/**
 * Cached raw test payloads keyed by card title for reuse in the modal detail view.
 *
 * @type {Record<string, unknown>}
 */
let testData = {};

/**
 * Build the HTML markup for one dashboard summary card.
 *
 * @remarks Preconditions:
 * - `metrics` must be an array of `{ label, value }` objects ready for direct rendering.
 * - `testType` must match the keys later stored in `testData` when details are available.
 *
 * @param {string} title - Human-readable card title.
 * @param {string} icon - Font Awesome class list for the card icon.
 * @param {string} status - Summary status such as `pass`, `fail`, or `warning`.
 * @param {Array<{label: string, value: (string|number)}>} metrics - Metrics to render inside the card body.
 * @param {string} testType - Lookup key used when opening the modal.
 * @param {boolean} hasDetails - Whether the card should expose a details modal.
 * @returns {string} HTML string for insertion into the results container.
 */
function createTestCard(title, icon, status, metrics, testType, hasDetails) {
    const statusClass = status.toLowerCase();
    const statusBadge = `<span class="status-badge ${statusClass}">${status}</span>`;
    const clickableClass = hasDetails ? 'clickable' : '';
    const interactionAttrs = clickableClass ?
        `data-test-type="${testType}" role="button" tabindex="0" aria-label="View ${title} details"` :
        '';
    
    let metricsHTML = '';
    metrics.forEach(metric => {
        metricsHTML += `
            <div class="test-metric">
                <span class="metric-label">${metric.label}:</span>
                <span class="metric-value">${metric.value}</span>
            </div>
        `;
    });

    const clickHint = clickableClass ? '<div class="clickable-hint"><i class="fas fa-hand-pointer"></i> Click to view details</div>' : '';

    return `
        <div class="test-card ${clickableClass}" ${interactionAttrs}>
            <div class="test-card-header">
                <div class="test-card-title">
                    <i class="${icon}"></i> ${title}
                </div>
                ${statusBadge}
            </div>
            <div class="test-card-body">
                ${metricsHTML}
                ${clickHint}
            </div>
        </div>
    `;
}

/**
 * Hide the details modal.
 *
 * @remarks Preconditions:
 * - The page must contain an element with id `detailsModal`.
 *
 * @returns {void}
 */
function closeModal() {
    document.getElementById('detailsModal').style.display = 'none';
}

// showTestDetails is called from dynamically generated onclick handlers
/* exported showTestDetails */
/**
 * Populate and display the modal for a specific test card.
 *
 * @remarks Preconditions:
 * - `testType` must already have a corresponding entry in `testData`.
 * - The modal title and body elements must exist in the document.
 *
 * @param {string} testType - The card/test identifier used as a `testData` key.
 * @returns {void}
 */
function showTestDetails(testType) {
    const modal = document.getElementById('detailsModal');
    const modalTitle = document.getElementById('modalTitle');
    const modalBody = document.getElementById('modalBody');
    
    const data = testData[testType];
    if (!data) return;

    modalTitle.textContent = `${testType} - Details`;
    try {
        modalBody.innerHTML = formatTestDetails(testType, data);
    } catch (error) {
        console.error(`Error displaying details for ${testType}:`, error);
        modalBody.innerHTML = `
            <div class="error-message">
                Could not render details for ${Utils.escapeHtml(testType)}. Check the console for the underlying error.
            </div>
        `;
    }
    modal.style.display = 'block';
}

/**
 * Attach click and keyboard handlers to any result cards that expose details.
 *
 * @remarks Preconditions:
 * - Cards generated by `createTestCard` use `data-test-type` when details are available.
 *
 * @returns {void}
 */
function bindCardInteractions() {
    const clickableCards = document.querySelectorAll('.test-card.clickable[data-test-type]');

    clickableCards.forEach(card => {
        card.addEventListener('click', () => {
            showTestDetails(card.dataset.testType);
        });

        card.addEventListener('keydown', event => {
            if (event.key === 'Enter' || event.key === ' ') {
                event.preventDefault();
                showTestDetails(card.dataset.testType);
            }
        });
    });
}

/**
 * Close the modal when the overlay itself is clicked.
 *
 * @remarks Preconditions:
 * - The details modal uses the overlay element itself as the click target for dismissal.
 *
 * @param {MouseEvent} event - Click event dispatched on the window.
 * @returns {void}
 */
window.onclick = function(event) {
    const modal = document.getElementById('detailsModal');
    if (event.target === modal) {
        closeModal();
    }
};

/**
 * Route a test payload to the formatter that knows how to render its details.
 *
 * @remarks Preconditions:
 * - `testType` must use the same labels assigned when building cards in `loadAllResults`.
 * - `data` is assumed to match the JSON schema for the selected test type.
 *
 * @param {string} testType - Dashboard test identifier.
 * @param {object} data - Raw JSON payload for the selected test.
 * @returns {string} HTML string for the modal body.
 */
function formatTestDetails(testType, data) {
    switch(testType) {
    case 'Code Validation':
        return formatValidationDetails(data);
    case 'Broken Links':
        return formatBrokenLinksDetails(data);
    case 'Axe Accessibility':
        return formatAxeDetails(data);
    case 'Pa11y Accessibility':
        return formatPa11yDetails(data);
    case 'WAVE Accessibility':
        return formatWaveDetails(data);
    case 'Lighthouse':
        return formatLighthouseDetails(data);
    case 'Browser Compatibility':
        return formatBrowserDetails(data);
    case 'Reading Age':
        return formatReadabilityDetails(data);
    case 'Colour Audit':
        return formatColourAuditDetails(data);
    case 'File Comments':
        return formatFileCommentsDetails(data);
    default:
        return '<p>No details available</p>';
    }
}

/**
 * Render validation report details for HTML, CSS, and JavaScript checks.
 *
 * @remarks Preconditions:
 * - `data.summary` and the per-file arrays are expected to follow the validation report schema.
 *
 * @param {object} data - Validation report payload.
 * @returns {string} HTML fragment for the modal.
 */
function formatValidationDetails(data) {
    let html = '';
    const typeLabels = {
        html: 'HTML Validation Issues',
        css: 'CSS Validation Issues',
        js: 'JavaScript Validation Issues'
    };

    const groupedFiles = Array.isArray(data.files) ?
        data.files.reduce((groups, file) => {
            if (!groups[file.type]) {
                groups[file.type] = [];
            }
            groups[file.type].push(file);
            return groups;
        }, {}) :
        {
            html: data.htmlFiles || [],
            css: data.cssFiles || [],
            js: data.jsFiles || []
        };

    ['html', 'css', 'js'].forEach(type => {
        const files = groupedFiles[type] || [];
        const filesWithIssues = files.filter(file => (file.errors && file.errors.length > 0) || (file.warnings && file.warnings.length > 0));

        if (Utils.isEmpty(filesWithIssues)) {
            return;
        }

        html += `<h3>${typeLabels[type]}</h3>`;
        filesWithIssues.forEach(file => {
            html += `<div class="error-item"><h4>${file.file}</h4>`;

            (file.errors || []).forEach(issue => {
                const lineText = issue.line ? `Line ${issue.line}${issue.column ? `:${issue.column}` : ''}` : 'Issue';
                html += `<div class="error-detail">❌ ${lineText}: ${issue.message}</div>`;
            });

            (file.warnings || []).forEach(issue => {
                if (typeof issue === 'string') {
                    html += `<div class="error-detail">⚠️ ${issue}</div>`;
                    return;
                }

                const lineText = issue.line ? `Line ${issue.line}${issue.column ? `:${issue.column}` : ''}` : 'Warning';
                html += `<div class="error-detail">⚠️ ${lineText}: ${issue.message}</div>`;
            });

            html += '</div>';
        });
    });

    return html || '<p>No validation errors found.</p>';
}

/**
 * Render broken-link details extracted from the link checker report.
 *
 * @remarks Preconditions:
 * - `data.pages` should contain page summaries with `links`, `brokenCount`, and `totalCount` data.
 *
 * @param {object} data - Broken-link report payload.
 * @returns {string} HTML fragment describing broken links, if any.
 */
function formatBrokenLinksDetails(data) {
    let brokenLinks = [];
    
    // Extract broken links from pages array
    if (data.pages && Array.isArray(data.pages)) {
        data.pages.forEach(page => {
            if (page.links && Array.isArray(page.links) && page.links.length > 0) {
                page.links.forEach(link => {
                    brokenLinks.push({
                        link: link.url || link.href || link.link || link,
                        status: link.status || link.statusCode || 'broken',
                        message: link.message || link.error || '',
                        page: page.url || page.page || page.file
                    });
                });
            }
        });
    }
    
    if (Utils.isEmpty(brokenLinks)) {
        return '<p>No broken links found. All links are working correctly!</p>';
    }
    
    let html = '<h3>Broken Links</h3>';
    brokenLinks.forEach(link => {
        html += `<div class="error-item">
            <h4>${link.link}</h4>
            <div class="error-detail">Status: ${link.status}</div>
            ${link.message ? `<div class="error-detail">${link.message}</div>` : ''}
            <div class="error-location">Found in: ${link.page}</div>
        </div>`;
    });
    return html;
}

/**
 * Render Axe accessibility violations grouped by rule identifier.
 *
 * @remarks Preconditions:
 * - `data.violations` must be an array of Axe-style violation objects when present.
 *
 * @param {object} data - Axe report payload.
 * @returns {string} HTML fragment for the modal.
 */
function formatAxeDetails(data) {
    if (!data.violations || Utils.isEmpty(data.violations)) {
        return '<p>No accessibility violations found.</p>';
    }
    
    let html = '<h3>Accessibility Violations</h3>';
    const grouped = {};
    
    data.violations.forEach(v => {
        if (!grouped[v.id]) {
            grouped[v.id] = {
                impact: v.impact,
                description: v.description,
                help: v.help,
                pages: []
            };
        }
        grouped[v.id].pages.push(`${v.pageUrl} (${v.theme}-${v.style}, ${v.viewport}px)`);
    });
    
    Object.entries(grouped).forEach(([id, info]) => {
        const impactIcon = info.impact === 'critical' ? '🔴' :
            info.impact === 'serious' ? '🟠' :
                info.impact === 'moderate' ? '🟡' : '⚪';
        html += `<div class="error-item">
            <h4>${impactIcon} ${id} (${info.impact})</h4>
            <div class="error-detail">${info.help}</div>
            <div class="error-location">Affected pages: ${info.pages.join(', ')}</div>
        </div>`;
    });
    
    return html;
}

/**
 * Render Pa11y issues separated into errors and warnings.
 *
 * @remarks Preconditions:
 * - `data.pages` must contain issue arrays using the expected Pa11y JSON schema.
 *
 * @param {object} data - Pa11y report payload.
 * @returns {string} HTML fragment for the modal.
 */
function formatPa11yDetails(data) {
    const errors = [];
    const warnings = [];

    data.pages.forEach(page => {
        page.issues.forEach(issue => {
            const item = {
                page: page.page || page.url || page.pageUrl || page.documentTitle,
                code: issue.code,
                message: issue.message,
                context: issue.context,
                selector: issue.selector
            };
            if (issue.type === 'error') errors.push(item);
            else if (issue.type === 'warning') warnings.push(item);
        });
    });
    
    let html = '';
    if (!Utils.isEmpty(errors)) {
        html += '<h3>Errors</h3>';
        errors.forEach(err => {
            html += `<div class="error-item">
                <h4>${err.code}</h4>
                <div class="error-detail">${err.message}</div>
                <div class="error-location">Page: ${err.page}<br>Selector: ${err.selector}</div>
            </div>`;
        });
    }
    
    if (!Utils.isEmpty(warnings)) {
        html += '<h3>Warnings</h3>';
        warnings.forEach(warn => {
            html += `<div class="warning-item">
                <h4>${warn.code}</h4>
                <div class="error-detail">${warn.message}</div>
                <div class="error-location">Page: ${warn.page}<br>Selector: ${warn.selector}</div>
            </div>`;
        });
    }
    
    return html || '<p>No issues found.</p>';
}

/**
 * Render WAVE accessibility results for pages with errors, alerts, or contrast issues.
 *
 * @remarks Preconditions:
 * - `data.pages` must contain WAVE page summaries with numeric issue counters.
 *
 * @param {object} data - WAVE report payload.
 * @returns {string} HTML fragment for the modal.
 */
function formatWaveDetails(data) {
    const pagesWithIssues = data.pages.filter(p => p.errors > 0 || p.alerts > 0 || p.contrast > 0);
    
    if (Utils.isEmpty(pagesWithIssues)) {
        return '<p>No WAVE accessibility issues found.</p>';
    }
    
    let html = '';
    pagesWithIssues.forEach(page => {
        // Use error-item for pages with errors, warning-item for pages with only alerts/contrast
        const itemClass = page.errors > 0 ? 'error-item' : 'warning-item';
        
        html += `<div class="${itemClass}">
            <h4>${page.url}</h4>
            <div class="error-detail">
                ${page.errors > 0 ? `❌ Errors: ${page.errors}` : ''}
                ${page.errors > 0 && (page.alerts > 0 || page.contrast > 0) ? ' | ' : ''}
                ${page.alerts > 0 ? `⚠️ Alerts: ${page.alerts}` : ''}
                ${page.alerts > 0 && page.contrast > 0 ? ' | ' : ''}
                ${page.contrast > 0 ? `🎨 Contrast: ${page.contrast}` : ''}
            </div>`;
        
        if (page.errorItems && page.errorItems.length > 0) {
            html += '<div style="margin-top: 0.5rem;"><strong>Errors:</strong>';
            page.errorItems.forEach(item => {
                html += `<div style="margin-left: 1rem;">❌ ${item.description} (${item.count})</div>`;
            });
            html += '</div>';
        }
        
        if (page.alertItems && page.alertItems.length > 0) {
            html += '<div style="margin-top: 0.5rem;"><strong>Alerts:</strong>';
            page.alertItems.forEach(item => {
                html += `<div style="margin-left: 1rem;">⚠️ ${item.description} (${item.count})</div>`;
            });
            html += '</div>';
        }
        
        if (page.contrastItems && page.contrastItems.length > 0) {
            html += '<div style="margin-top: 0.5rem;"><strong>Contrast Issues:</strong>';
            page.contrastItems.forEach(item => {
                html += `<div style="margin-left: 1rem;">🎨 ${item.description} (${item.count})</div>`;
            });
            html += '</div>';
        }
        
        html += `<div class="error-location">Theme: ${page.theme}, Style: ${page.style}, Viewport: ${page.viewport}px</div>`;
        html += '</div>';
    });
    
    return html;
}

/**
 * Render Lighthouse audit failures for any pages that did not achieve a clean run.
 *
 * @remarks Preconditions:
 * - `data.pages` should contain a `failedAudits` array for each tested page.
 *
 * @param {object} data - Lighthouse report payload.
 * @returns {string} HTML fragment for the modal.
 */
function formatLighthouseDetails(data) {
    const pagesWithErrors = data.pages.filter(p => p.score < 0.9);
    const pagesWithWarnings = data.pages.filter(p => p.score >= 0.9 && p.score < 1.0);
    
    if (pagesWithErrors.length === 0 && pagesWithWarnings.length === 0) {
        return '<p>All pages passed Lighthouse audits with 100% score.</p>';
    }
    
    let html = '';
    
    // Show errors (< 90%)
    if (pagesWithErrors.length > 0) {
        html += '<h3>❌ Pages Below 90% Accessibility</h3>';
        pagesWithErrors.forEach(page => {
            html += `<div class="error-item">
                <h4>${page.url} [${page.viewport}px, ${page.style}-${page.theme}]</h4>
                <div class="error-detail">Score: ${Math.round(page.score * 100)}%</div>`;
            
            if (page.failedAudits && page.failedAudits.length > 0) {
                html += '<div style="margin-top: 0.5rem;">';
                page.failedAudits.forEach(audit => {
                    html += `<div>• ${audit.title || audit}</div>`;
                });
                html += '</div>';
            }
            html += '</div>';
        });
    }
    
    // Show warnings (90-99%)
    if (pagesWithWarnings.length > 0) {
        html += '<h3>⚠️ Pages Between 90-99% Accessibility</h3>';
        pagesWithWarnings.forEach(page => {
            html += `<div class="warning-item">
                <h4>${page.url} [${page.viewport}px, ${page.style}-${page.theme}]</h4>
                <div class="warning-detail">Score: ${Math.round(page.score * 100)}%</div>`;
            
            if (page.failedAudits && page.failedAudits.length > 0) {
                html += '<div style="margin-top: 0.5rem;">';
                page.failedAudits.forEach(audit => {
                    html += `<div>• ${audit.title || audit}</div>`;
                });
                html += '</div>';
            }
            html += '</div>';
        });
    }
    
    return html;
}

/**
 * Render failed browser-engine results from the cross-browser test runner.
 *
 * @remarks Preconditions:
 * - `data` must expose either a `browsers` array or a `results` array.
 *
 * @param {object} data - Browser test payload.
 * @returns {string} HTML fragment for the modal.
 */
function formatBrowserDetails(data) {
    const browserList = data.browsers || data.results || [];
    const failed = browserList.filter(b => b.status === 'failed' || b.passed === false);
    
    if (Utils.isEmpty(failed)) {
        return '<p>All browser tests passed.</p>';
    }
    
    let html = '<h3>Failed Browsers</h3>';
    failed.forEach(browser => {
        html += `<div class="error-item">
            <h4>${browser.browser || browser.name || 'Unknown Browser'}</h4>
            <div class="error-detail">${browser.error || browser.message || 'Test failed'}</div>
        </div>`;
    });
    
    return html;
}

/**
 * Render readability issues for pages above the target reading grade.
 *
 * @remarks Preconditions:
 * - `data.pages` must contain readability metrics with `averageGradeLevel` when present.
 *
 * @param {object} data - Readability report payload.
 * @returns {string} HTML fragment for the modal.
 */
function formatReadabilityDetails(data) {
    if (!data.pages || Utils.isEmpty(data.pages)) {
        return '<p>No readability data available.</p>';
    }
    
    const highGradePages = data.pages.filter(p => p.averageGradeLevel > 12);
    
    if (Utils.isEmpty(highGradePages)) {
        return '<p>All pages have appropriate reading levels.</p>';
    }
    
    let html = '<h3>Pages Above Grade 12 Reading Level</h3>';
    highGradePages.forEach(page => {
        html += `<div class="warning-item">
            <h4>${page.page || page.file || 'Unknown Page'}</h4>
            <div class="error-detail">
                Grade Level: ${page.averageGradeLevel.toFixed(1)} | 
                Words: ${page.wordCount} | 
                Average Sentence Length: ${page.averageSentenceLength || 'n/a'}
            </div>
        </div>`;
    });
    
    return html;
}

/**
 * Render file comment check results, displaying files missing headers or required fields.
 *
 * @remarks Preconditions:
 * - `data` is expected to have a `files` array and `summary` object following the file-comments-check schema.
 *
 * @param {object} data - File comments check payload.
 * @returns {string} HTML fragment for the modal.
 */
function formatFileCommentsDetails(data) {
    const filesWithIssues = data.files || [];
    
    if (Utils.isEmpty(filesWithIssues)) {
        return '<p>All files have proper header comments with required fields.</p>';
    }
    
    let html = '<h3>Files with Issues</h3>';
    filesWithIssues.forEach(file => {
        html += `<div class="error-item">
            <h4>${file.file}</h4>`;
        
        if (file.issues && file.issues.length > 0) {
            file.issues.forEach(issue => {
                if (issue.type === 'missing-header') {
                    html += `<div class="error-detail">❌ Missing header comment block</div>`;
                } else if (issue.type === 'missing-fields') {
                    const fields = issue.missingFields ? issue.missingFields.join(', ') : '';
                    html += `<div class="error-detail">⚠️ Missing required fields: ${fields}</div>`;
                } else {
                    html += `<div class="error-detail">${issue.message}</div>`;
                }
            });
        }
        
        html += '</div>';
    });
    
    return html;
}

/**
 * Render colour-audit findings covering hardcoded colours, direct theme variables, and missing setup.
 *
 * @remarks Preconditions:
 * - `data` is expected to follow the `colour-audit-report.json` schema.
 *
 * @param {object} data - Colour audit payload.
 * @returns {string} HTML fragment for the modal.
 */
function formatColourAuditDetails(data) {
    let html = '';
    
    if (data.hardcodedColours && data.hardcodedColours.length > 0) {
        html += '<h3>Hardcoded Colours</h3>';
        data.hardcodedColours.forEach(item => {
            html += `<div class="error-item">
                <h4>${item.file}</h4>
                <div class="error-detail">Line ${item.line}: ${item.value}</div>
                ${item.context ? `<div class="error-location">${item.context}</div>` : ''}
            </div>`;
        });
    }
    
    if (data.themeSpecificVars && data.themeSpecificVars.length > 0) {
        html += '<h3>Theme-Specific Variables</h3>';
        data.themeSpecificVars.forEach(item => {
            html += `<div class="warning-item">
                <h4>${item.file}</h4>
                <div class="error-detail">Line ${item.line}: ${item.variable}</div>
                <div class="error-location">Should use generic variables like --colour-page-background instead</div>
            </div>`;
        });
    }
    
    if (data.missingThemeSystem && data.missingThemeSystem.length > 0) {
        html += '<h3>Missing Theme System</h3>';
        data.missingThemeSystem.forEach(item => {
            html += `<div class="warning-item">
                <h4>${item.file}</h4>
                <div class="error-detail">${item.message || 'Not using theme variable system'}</div>
            </div>`;
        });
    }
    
    return html || '<p>No colour issues found. All colours use the theme system correctly.</p>';
}

/**
 * Load every available dashboard result file, update summary metrics, and render the cards.
 *
 * @remarks Preconditions:
 * - The diagnostics page must contain the expected container and summary elements by id.
 * - Missing JSON files are tolerated; the dashboard simply omits cards for reports that were not generated.
 * - Individual result files must follow the schemas assumed by the formatter functions above.
 *
 * @returns {Promise<void>} Resolves after the dashboard has been populated.
 */
async function loadAllResults() {
    const resultsContainer = document.getElementById('test-results');
    resultsContainer.innerHTML = '<div class="loading"><i class="fas fa-spinner fa-spin"></i> Loading test results...</div>';

    let totalTests = 0;
    let passedTests = 0;
    let failedTests = 0;
    let totalWarnings = 0;

    const cards = [];

    // Load Validation Results
    const validation = await Utils.loadJSON('../diagnostics/test-results/validation-results.json');
    if (validation) {
        const hasErrors = validation.summary.htmlErrors > 0 || 
                        validation.summary.cssErrors > 0 || 
                        validation.summary.jsErrors > 0;
        const status = hasErrors ? 'fail' : 'pass';
        
        totalTests++;
        if (status === 'pass') passedTests++;
        else failedTests++;
        totalWarnings += validation.summary.htmlWarnings + 
                       validation.summary.cssWarnings + 
                       validation.summary.jsWarnings;

        testData['Code Validation'] = validation;
        cards.push(createTestCard(
            'Code Validation',
            'fas fa-check-circle',
            status,
            [
                { label: 'Files Checked', value: validation.summary.filesChecked || 0 },
                { label: 'HTML Errors', value: validation.summary.htmlErrors },
                { label: 'CSS Errors', value: validation.summary.cssErrors },
                { label: 'JS Errors', value: validation.summary.jsErrors },
                { label: 'Total Warnings', value: totalWarnings }
            ],
            'Code Validation',
            hasErrors || totalWarnings > 0
        ));
    }

    // Load Broken Links Results
    const links = await Utils.loadJSON('../diagnostics/test-results/broken-links-results.json');
    if (links) {
        const totalBroken = links.pages.reduce((sum, page) => sum + page.brokenCount, 0);
        const totalLinks = links.pages.reduce((sum, page) => sum + page.totalCount, 0);
        const timeoutWarnings = links.summary?.timeoutLinks || 0;
        const status = totalBroken === 0 ? 'pass' : 'fail';
        
        totalTests++;
        if (status === 'pass') passedTests++;
        else failedTests++;

        testData['Broken Links'] = links;
        cards.push(createTestCard(
            'Broken Links Check',
            'fas fa-link',
            status,
            [
                { label: 'Pages Checked', value: links.pages.length },
                { label: 'Total Links', value: totalLinks },
                { label: 'Broken Links', value: totalBroken },
                { label: 'Timeout Warnings', value: timeoutWarnings }
            ],
            'Broken Links',
            totalBroken > 0
        ));
    }

    // Load Axe Results
    const axe = await Utils.loadJSON('../diagnostics/test-results/axe-results.json');
    if (axe) {
        // Count violations across all pages if structure has pages array
        let totalViolations = 0;
        let totalPasses = 0;
        let totalIncomplete = 0;
        let pagesTestedCount = 0;
        
        if (Array.isArray(axe.violations)) {
            // Direct violations array
            totalViolations = axe.violations.length;
            
            // Calculate passes - could be array of objects with counts or simple array
            if (Array.isArray(axe.passes)) {
                totalPasses = axe.passes.reduce((sum, p) => {
                    // If passes are stored as {pageUrl, count}, sum the counts
                    // Otherwise just count the array length
                    return sum + (p.count || 1);
                }, 0);
            }
            
            totalIncomplete = axe.incomplete ? axe.incomplete.length : 0;
            
            // Get metadata if available
            if (axe.metadata && axe.metadata.pagesTestedCount) {
                pagesTestedCount = axe.metadata.pagesTestedCount;
            }
        } else if (axe.pages && Array.isArray(axe.pages)) {
            // Pages array structure
            axe.pages.forEach(page => {
                totalViolations += page.violations ? page.violations.length : 0;
                totalPasses += page.passes ? page.passes.length : 0;
                totalIncomplete += page.incomplete ? page.incomplete.length : 0;
            });
            pagesTestedCount = axe.pages.length;
        }
        
        const status = totalViolations === 0 ? 'pass' : 'fail';
        
        totalTests++;
        if (status === 'pass') passedTests++;
        else failedTests++;

        const metrics = [
            { label: 'Total Violations', value: totalViolations },
            { label: 'Total Passes', value: totalPasses },
            { label: 'Incomplete', value: totalIncomplete }
        ];
        
        // Add pages tested count if available
        if (pagesTestedCount > 0) {
            metrics.unshift({ label: 'Pages Tested', value: pagesTestedCount });
        }

        testData['Axe Accessibility'] = axe;
        cards.push(createTestCard(
            'Axe Accessibility',
            'fas fa-universal-access',
            status,
            metrics,
            'Axe Accessibility',
            totalViolations > 0
        ));
    }

    // Load Pa11y Results
    const pa11y = await Utils.loadJSON('../diagnostics/test-results/pa11y-results.json');
    if (pa11y) {
        const totalErrors = pa11y.pages.reduce((sum, page) => 
            sum + page.issues.filter(i => i.type === 'error').length, 0);
        const totalWarningsP = pa11y.pages.reduce((sum, page) => 
            sum + page.issues.filter(i => i.type === 'warning').length, 0);
        const status = totalErrors === 0 ? 'pass' : 'fail';
        
        totalTests++;
        if (status === 'pass') passedTests++;
        else failedTests++;
        totalWarnings += totalWarningsP;

        testData['Pa11y Accessibility'] = pa11y;
        cards.push(createTestCard(
            'Pa11y Accessibility',
            'fas fa-wheelchair',
            status,
            [
                { label: 'Pages Tested', value: pa11y.pages.length },
                { label: 'Errors', value: totalErrors },
                { label: 'Warnings', value: totalWarningsP }
            ],
            'Pa11y Accessibility',
            totalErrors > 0 || totalWarningsP > 0
        ));
    }

    // Load WAVE Results
    const wave = await Utils.loadJSON('../diagnostics/test-results/wave-results.json');
    if (wave) {
        const totalErrorsW = wave.pages.reduce((sum, page) => sum + (page.errors || 0), 0);
        const totalAlertsW = wave.pages.reduce((sum, page) => sum + (page.alerts || 0), 0);
        const totalContrastW = wave.pages.reduce((sum, page) => sum + (page.contrast || 0), 0);
        
        // Determine status: fail if errors, warning if alerts/contrast, pass otherwise
        let status = 'pass';
        if (totalErrorsW > 0) {
            status = 'fail';
        } else if (totalAlertsW > 0 || totalContrastW > 0) {
            status = 'warning';
        }
        
        totalTests++;
        if (status === 'pass') passedTests++;
        else if (status === 'fail') failedTests++;
        else if (status === 'warning') totalWarnings++;
        totalWarnings += totalAlertsW;

        testData['WAVE Accessibility'] = wave;
        cards.push(createTestCard(
            'WAVE Accessibility',
            'fas fa-water',
            status,
            [
                { label: 'Pages Tested', value: wave.pages.length },
                { label: 'Errors', value: totalErrorsW },
                { label: 'Alerts', value: totalAlertsW },
                { label: 'Contrast Issues', value: totalContrastW }
            ],
            'WAVE Accessibility',
            totalErrorsW > 0 || totalAlertsW > 0 || totalContrastW > 0
        ));
    }

    // Load Lighthouse Results
    const lighthouse = await Utils.loadJSON('../diagnostics/test-results/lighthouse-results.json');
    if (lighthouse) {
        const avgScore = lighthouse.pages.length > 0 ?
            Math.round((lighthouse.pages.reduce((sum, page) => sum + page.score, 0) / lighthouse.pages.length) * 100) :
            0;
        const pagesWithErrors = lighthouse.pages.filter(p => p.score < 0.9).length;
        const pagesWithWarnings = lighthouse.pages.filter(p => p.score >= 0.9 && p.score < 1.0).length;
        const status = pagesWithErrors > 0 ? 'fail' : (pagesWithWarnings > 0 ? 'warning' : 'pass');
        
        totalTests++;
        if (status === 'pass') passedTests++;
        else if (status === 'fail') failedTests++;
        else if (status === 'warning') totalWarnings++;

        testData.Lighthouse = lighthouse;
        cards.push(createTestCard(
            'Lighthouse',
            'fas fa-lightbulb',
            status,
            [
                { label: 'Pages Tested', value: lighthouse.pages.length },
                { label: 'Average Score', value: `${avgScore}%` },
                { label: 'Errors (<90%)', value: pagesWithErrors },
                { label: 'Warnings (90-99%)', value: pagesWithWarnings }
            ],
            'Lighthouse',
            pagesWithErrors > 0 || pagesWithWarnings > 0
        ));
    }

    // Load Browser Results
    const browser = await Utils.loadJSON('../diagnostics/test-results/browser-results.json');
    if (browser) {
        // Handle both 'browsers' and 'results' array structures
        const browserList = browser.browsers || browser.results || [];
        const passed = browserList.filter(b => b.status === 'passed' || b.passed === true).length;
        const failed = browserList.filter(b => b.status === 'failed' || b.passed === false).length;
        const status = failed === 0 ? 'pass' : 'fail';
        
        totalTests++;
        if (status === 'pass') passedTests++;
        else failedTests++;

        testData['Browser Compatibility'] = browser;
        cards.push(createTestCard(
            'Browser Compatibility',
            'fas fa-browser',
            status,
            [
                { label: 'Browsers Tested', value: browserList.length },
                { label: 'Passed', value: passed },
                { label: 'Failed', value: failed }
            ],
            'Browser Compatibility',
            failed > 0
        ));
    }

    // Load Readability Results
    const readability = await Utils.loadJSON('../diagnostics/test-results/readability-results.json');
    if (readability) {
        let avgGrade = 0;
        let totalWords = 0;
        
        if (readability.pages && Array.isArray(readability.pages) && readability.pages.length > 0) {
            // Calculate from pages array
            totalWords = readability.pages.reduce((sum, page) => sum + (page.wordCount || 0), 0);
            const totalGrade = readability.pages.reduce((sum, page) => sum + (page.averageGradeLevel || 0), 0);
            avgGrade = (totalGrade / readability.pages.length).toFixed(1);
        } else {
            // Fallback to root level properties if they exist
            avgGrade = readability.averageGradeLevel || 0;
            totalWords = readability.totalWords || 0;
        }
        
        const status = avgGrade <= 12 ? 'pass' : 'warning';
        
        totalTests++;
        if (status === 'pass') passedTests++;
        else if (status === 'warning') totalWarnings++;

        testData['Reading Age'] = readability;
        cards.push(createTestCard(
            'Reading Age',
            'fas fa-book-reader',
            status,
            [
                { label: 'Pages Analysed', value: readability.pages ? readability.pages.length : 0 },
                { label: 'Average Grade Level', value: avgGrade },
                { label: 'Total Words', value: totalWords }
            ],
            'Reading Age',
            avgGrade > 12
        ));
    }

    // Load Colour Audit Results
    const colourAudit = await Utils.loadJSON('../diagnostics/test-results/colour-audit-report.json');
    if (colourAudit) {
        const totalIssues = (colourAudit.hardcodedColours ? colourAudit.hardcodedColours.length : 0) +
                          (colourAudit.themeSpecificVars ? colourAudit.themeSpecificVars.length : 0) +
                          (colourAudit.missingThemeSystem ? colourAudit.missingThemeSystem.length : 0);
        const status = totalIssues === 0 ? 'pass' : 'fail';
        
        totalTests++;
        if (status === 'pass') passedTests++;
        else failedTests++;

        testData['Colour Audit'] = colourAudit;
        cards.push(createTestCard(
            'Colour Audit',
            'fas fa-palette',
            status,
            [
                { label: 'Hardcoded Colours', value: colourAudit.hardcodedColours ? colourAudit.hardcodedColours.length : 0 },
                { label: 'Theme-Specific Vars', value: colourAudit.themeSpecificVars ? colourAudit.themeSpecificVars.length : 0 },
                { label: 'Missing Theme System', value: colourAudit.missingThemeSystem ? colourAudit.missingThemeSystem.length : 0 },
                { label: 'Total Issues', value: totalIssues }
            ],
            'Colour Audit',
            totalIssues > 0
        ));
    }

    // Load File Comments Check Results
    const fileComments = await Utils.loadJSON('../diagnostics/test-results/file-comments-check-results.json');
    if (fileComments && fileComments.summary) {
        const status = fileComments.summary.filesWithIssues === 0 ? 'pass' : 'fail';
        
        totalTests++;
        if (status === 'pass') passedTests++;
        else failedTests++;

        testData['File Comments'] = fileComments;
        cards.push(createTestCard(
            'File Comments',
            'fas fa-file-alt',
            status,
            [
                { label: 'Total Files Checked', value: fileComments.summary.totalFiles },
                { label: 'Files with Issues', value: fileComments.summary.filesWithIssues },
                { label: 'Missing Headers', value: fileComments.summary.missingHeaderBlocks },
                { label: 'Missing Fields', value: fileComments.summary.missingRequiredFields }
            ],
            'File Comments',
            fileComments.summary.filesWithIssues > 0
        ));
    }

    // Update summary
    document.getElementById('total-tests').textContent = totalTests;
    document.getElementById('passed-tests').textContent = passedTests;
    document.getElementById('failed-tests').textContent = failedTests;
    document.getElementById('warnings').textContent = totalWarnings;

    // Display cards
    if (cards.length > 0) {
        resultsContainer.innerHTML = cards.join('');
        bindCardInteractions();
    } else {
        resultsContainer.innerHTML = '<div class="error-message">No test results found. Please run tests first.</div>';
    }

    // Update timestamp
    const now = new Date();
    document.getElementById('timestamp').textContent = `Last updated: ${now.toLocaleString()}`;
}

// Load results on page load
window.addEventListener('DOMContentLoaded', loadAllResults);
